import React, { useState, useCallback, useEffect } from "react";
import {
  Modal,
  FileUploaderDropContainer,
  FileUploaderItem,
  Select,
  SelectItem,
  Button,
  InlineNotification,
  Tag,
  Loading,
  StructuredListWrapper,
  StructuredListHead,
  StructuredListRow,
  StructuredListCell,
  StructuredListBody,
  Accordion,
  AccordionItem,
} from "@carbon/react";
import { Upload, Checkmark, Warning, Information } from "@carbon/react/icons";
import { FormattedMessage, useIntl } from "react-intl";
import config from "../../../config.json";
import "./NotebookWorkflow.css";

/**
 * Expected dataPoints for Immunology Sample Reception Manifest.
 * Aligned with the immunology workflow reception metadata requirements.
 */
const EXPECTED_DATA_POINTS = {
  required: [
    {
      key: "uniqueParentSampleId",
      label: "Unique Parent Sample Identifier",
      description:
        "Unique identifier assigned at reception (can be auto-generated if not provided)",
      example: "IMM-2024-001-A",
    },
    {
      key: "projectNameId",
      label: "Project Name/ID",
      description: "Study or project identifier",
      example: "PROJ-VAC-2024",
    },
    {
      key: "deliveryManifestReference",
      label: "Delivery Manifest Reference",
      description: "Reference number from the delivery manifest",
      example: "DM-2024-12-001",
    },
    {
      key: "collectionDateTime",
      label: "Collection Date & Time",
      description: "Date and time of sample collection (YYYY-MM-DD HH:MM)",
      example: "2024-01-15 09:30",
    },
    {
      key: "receptionDateTime",
      label: "Reception Date & Time",
      description:
        "Date and time of sample reception (YYYY-MM-DD HH:MM or 'now')",
      example: "2024-01-16 14:00",
    },
    {
      key: "sourceOrigin",
      label: "Source/Origin",
      description: "Facility or study site where sample was collected",
      example: "Addis Ababa Health Center",
    },
  ],
  sampleType: {
    key: "sampleType",
    label: "Sample Type",
    description:
      "Type of immunology sample (validated against Immunology lab types)",
    example: "Whole Blood, PBMC, Serum, Plasma, etc.",
  },
  optional: [
    {
      key: "sampleVolume",
      label: "Sample Volume/Quantity",
      description: "Volume or quantity of the sample (with units)",
      example: "5 mL, 2x10^6 cells",
    },
    {
      key: "storageConditionOnArrival",
      label: "Storage Condition on Arrival",
      description:
        "Storage condition when received (Ambient, Refrigerated, Frozen, Dry Ice, Liquid Nitrogen)",
      example: "Refrigerated (2-8C)",
    },
    {
      key: "transportTemperature",
      label: "Transport Temperature",
      description: "Temperature during transport (in Celsius)",
      example: "4C, -20C, -80C",
    },
    {
      key: "receivingPersonnelName",
      label: "Receiving Personnel Name",
      description: "Name of person who received the sample",
      example: "Dr. Sarah Bekele",
    },
    {
      key: "manifestVerificationStatus",
      label: "Delivery Manifest Verification Status",
      description:
        "Status of manifest verification (Verified, Pending, Discrepancy)",
      example: "Verified",
    },
    {
      key: "patientId",
      label: "Patient/Subject ID",
      description: "Patient or study subject identifier (if applicable)",
      example: "SUBJ-001",
    },
    {
      key: "notes",
      label: "Notes/Comments",
      description: "Additional notes or observations",
      example: "Sample received in good condition",
    },
  ],
  autoGenerated: [
    {
      key: "accessionNumber",
      label: "Accession Number",
      description: "System-generated laboratory accession number",
    },
    {
      key: "barcodeQrCode",
      label: "Barcode/QR Code",
      description: "System-generated scannable identifier",
    },
  ],
};

/**
 * ImmunologyManifestImportModal - CSV import modal for Immunology workflow.
 * Supports mapping immunology-specific reception metadata columns.
 */
function ImmunologyManifestImportModal({
  open,
  onClose,
  entryId,
  onImportSuccess,
}) {
  const intl = useIntl();

  const [file, setFile] = useState(null);
  const [fileError, setFileError] = useState(null);
  const [csvHeaders, setCsvHeaders] = useState([]);
  const [columnMapping, setColumnMapping] = useState({
    // Required fields
    uniqueParentSampleIdColumn: "",
    projectNameIdColumn: "",
    deliveryManifestReferenceColumn: "",
    collectionDateTimeColumn: "",
    receptionDateTimeColumn: "",
    sourceOriginColumn: "",
    // Sample type (validated against Immunology lab types)
    sampleTypeColumn: "",
    // Optional fields
    sampleVolumeColumn: "",
    storageConditionOnArrivalColumn: "",
    transportTemperatureColumn: "",
    receivingPersonnelNameColumn: "",
    manifestVerificationStatusColumn: "",
    patientIdColumn: "",
    notesColumn: "",
  });

  const [step, setStep] = useState(1);
  const [previewData, setPreviewData] = useState(null);
  const [previewErrors, setPreviewErrors] = useState([]);
  const [isPreviewLoading, setIsPreviewLoading] = useState(false);
  const [isImporting, setIsImporting] = useState(false);

  // Dynamic sample types from backend
  const [validSampleTypes, setValidSampleTypes] = useState([]);
  const [isSampleTypesLoading, setIsSampleTypesLoading] = useState(false);

  // Fetch valid sample types from backend when modal opens
  useEffect(() => {
    if (open) {
      setIsSampleTypesLoading(true);
      fetch(`${config.serverBaseUrl}/rest/notebook/immunology/sample-types`, {
        method: "GET",
        credentials: "include",
        headers: {
          "X-CSRF-Token": localStorage.getItem("CSRF"),
        },
      })
        .then((response) => response.json())
        .then((data) => {
          if (data.sampleTypes) {
            setValidSampleTypes(data.sampleTypes.map((st) => st.description));
          }
        })
        .catch((error) => {
          console.error("Failed to fetch sample types:", error);
          // Fallback to empty array - validation will still happen on backend
          setValidSampleTypes([]);
        })
        .finally(() => {
          setIsSampleTypesLoading(false);
        });
    }
  }, [open]);

  /**
   * Auto-detect and map CSV columns based on header names.
   * Matches against expected column keys (case-insensitive).
   */
  const autoMapColumns = useCallback((headers) => {
    // Map of expected column keys to their form field names
    const columnKeyToField = {
      uniqueparentsampleid: "uniqueParentSampleIdColumn",
      uniqueparentsampleidentifier: "uniqueParentSampleIdColumn",
      sampleid: "uniqueParentSampleIdColumn",
      projectnameid: "projectNameIdColumn",
      projectname: "projectNameIdColumn",
      projectid: "projectNameIdColumn",
      project: "projectNameIdColumn",
      deliverymanifestreference: "deliveryManifestReferenceColumn",
      manifestreference: "deliveryManifestReferenceColumn",
      manifestref: "deliveryManifestReferenceColumn",
      collectiondatetime: "collectionDateTimeColumn",
      collectiondate: "collectionDateTimeColumn",
      receptiondatetime: "receptionDateTimeColumn",
      receptiondate: "receptionDateTimeColumn",
      receiveddate: "receptionDateTimeColumn",
      sourceorigin: "sourceOriginColumn",
      source: "sourceOriginColumn",
      origin: "sourceOriginColumn",
      facility: "sourceOriginColumn",
      studysite: "sourceOriginColumn",
      sampletype: "sampleTypeColumn",
      type: "sampleTypeColumn",
      samplevolume: "sampleVolumeColumn",
      volume: "sampleVolumeColumn",
      quantity: "sampleVolumeColumn",
      storageconditiononarrival: "storageConditionOnArrivalColumn",
      storagecondition: "storageConditionOnArrivalColumn",
      storage: "storageConditionOnArrivalColumn",
      transporttemperature: "transportTemperatureColumn",
      temperature: "transportTemperatureColumn",
      temp: "transportTemperatureColumn",
      receivingpersonnelname: "receivingPersonnelNameColumn",
      receivedby: "receivingPersonnelNameColumn",
      receiver: "receivingPersonnelNameColumn",
      manifestverificationstatus: "manifestVerificationStatusColumn",
      verificationstatus: "manifestVerificationStatusColumn",
      verified: "manifestVerificationStatusColumn",
      patientid: "patientIdColumn",
      subjectid: "patientIdColumn",
      notes: "notesColumn",
      comments: "notesColumn",
    };

    const newMapping = {
      uniqueParentSampleIdColumn: "",
      projectNameIdColumn: "",
      deliveryManifestReferenceColumn: "",
      collectionDateTimeColumn: "",
      receptionDateTimeColumn: "",
      sourceOriginColumn: "",
      sampleTypeColumn: "",
      sampleVolumeColumn: "",
      storageConditionOnArrivalColumn: "",
      transportTemperatureColumn: "",
      receivingPersonnelNameColumn: "",
      manifestVerificationStatusColumn: "",
      patientIdColumn: "",
      notesColumn: "",
    };

    headers.forEach((header) => {
      // Normalize header: lowercase, remove spaces/underscores/hyphens
      const normalizedHeader = header
        .toLowerCase()
        .replace(/[\s_-]/g, "")
        .replace(/[/\\]/g, "");

      const fieldName = columnKeyToField[normalizedHeader];
      if (fieldName) {
        newMapping[fieldName] = header;
      }
    });

    return newMapping;
  }, []);

  const handleFileAdded = useCallback(
    (event, { addedFiles }) => {
      const addedFile = addedFiles[0];
      if (!addedFile) return;

      if (!addedFile.name.endsWith(".csv")) {
        setFileError(
          intl.formatMessage({
            id: "notebook.immunology.manifest.error.invalidFileType",
            defaultMessage: "Please upload a CSV file",
          }),
        );
        return;
      }

      setFile(addedFile);
      setFileError(null);

      const reader = new FileReader();
      reader.onload = (e) => {
        const text = e.target.result;
        const firstLine = text.split("\n")[0];
        const headers = firstLine
          .split(",")
          .map((h) => h.trim().replace(/"/g, ""));
        setCsvHeaders(headers);

        // Auto-map columns based on header names
        const autoMappedColumns = autoMapColumns(headers);
        setColumnMapping(autoMappedColumns);

        setStep(2);
      };
      reader.readAsText(addedFile);
    },
    [intl, autoMapColumns],
  );

  const handleRemoveFile = () => {
    setFile(null);
    setCsvHeaders([]);
    setColumnMapping({
      uniqueParentSampleIdColumn: "",
      projectNameIdColumn: "",
      deliveryManifestReferenceColumn: "",
      collectionDateTimeColumn: "",
      receptionDateTimeColumn: "",
      sourceOriginColumn: "",
      sampleTypeColumn: "",
      sampleVolumeColumn: "",
      storageConditionOnArrivalColumn: "",
      transportTemperatureColumn: "",
      receivingPersonnelNameColumn: "",
      manifestVerificationStatusColumn: "",
      patientIdColumn: "",
      notesColumn: "",
    });
    setPreviewData(null);
    setPreviewErrors([]);
    setStep(1);
  };

  const handleMappingChange = (field, value) => {
    setColumnMapping((prev) => ({ ...prev, [field]: value }));
  };

  // All 6 required fields must be mapped
  const requiredColumnsMapped =
    columnMapping.uniqueParentSampleIdColumn &&
    columnMapping.projectNameIdColumn &&
    columnMapping.deliveryManifestReferenceColumn &&
    columnMapping.collectionDateTimeColumn &&
    columnMapping.receptionDateTimeColumn &&
    columnMapping.sourceOriginColumn;

  const buildFormData = () => {
    const formData = new FormData();
    formData.append("file", file);
    formData.append(
      "mapping",
      new Blob([JSON.stringify(columnMapping)], { type: "application/json" }),
    );
    return formData;
  };

  const handlePreview = async () => {
    if (!file || !entryId) return;
    setIsPreviewLoading(true);
    setPreviewErrors([]);

    try {
      const endpoint = `${config.serverBaseUrl}/rest/notebook/immunology/entry/${entryId}/samples/preview-manifest`;
      const response = await fetch(endpoint, {
        method: "POST",
        body: buildFormData(),
        credentials: "include",
        headers: {
          "X-CSRF-Token": localStorage.getItem("CSRF"),
        },
      });

      const data = await response.json();
      if (response.ok) {
        setPreviewData(data);
        setPreviewErrors(data.errors || []);
        setStep(3);
      } else {
        setPreviewErrors(
          data.errors || [
            {
              rowNumber: 0,
              column: "file",
              message: data.error || "Preview failed",
            },
          ],
        );
      }
    } catch (error) {
      setPreviewErrors([
        { rowNumber: 0, column: "file", message: error.message },
      ]);
    } finally {
      setIsPreviewLoading(false);
    }
  };

  const handleImport = async () => {
    if (!file || !entryId) return;
    setIsImporting(true);
    setPreviewErrors([]);

    try {
      const endpoint = `${config.serverBaseUrl}/rest/notebook/immunology/entry/${entryId}/samples/create-from-manifest`;
      const response = await fetch(endpoint, {
        method: "POST",
        body: buildFormData(),
        credentials: "include",
        headers: {
          "X-CSRF-Token": localStorage.getItem("CSRF"),
        },
      });

      const data = await response.json();
      if (response.ok && data.success) {
        setStep(4);
        if (onImportSuccess) {
          onImportSuccess(data);
        }
      } else {
        setPreviewErrors(
          data.errors || [
            {
              rowNumber: 0,
              column: "import",
              message: data.error || "Import failed",
            },
          ],
        );
      }
    } catch (error) {
      setPreviewErrors([
        { rowNumber: 0, column: "import", message: error.message },
      ]);
    } finally {
      setIsImporting(false);
    }
  };

  const handleClose = () => {
    handleRemoveFile();
    onClose();
  };

  const mappingField = (field, labelId) => (
    <Select
      id={`mapping-${field}`}
      labelText={intl.formatMessage({ id: labelId })}
      value={columnMapping[field]}
      onChange={(e) => handleMappingChange(field, e.target.value)}
    >
      <SelectItem value="" text={intl.formatMessage({ id: "label.select" })} />
      {csvHeaders.map((header) => (
        <SelectItem key={header} value={header} text={header} />
      ))}
    </Select>
  );

  return (
    <Modal
      open={open}
      onRequestClose={handleClose}
      modalHeading={intl.formatMessage({
        id: "notebook.immunology.manifest.title",
        defaultMessage: "Import Immunology Samples from Delivery Manifest",
      })}
      primaryButtonText={
        step === 1
          ? intl.formatMessage({ id: "label.button.next" })
          : step === 2
            ? intl.formatMessage({ id: "notebook.manifest.preview" })
            : step === 3
              ? intl.formatMessage({ id: "notebook.manifest.import" })
              : intl.formatMessage({ id: "label.button.close" })
      }
      secondaryButtonText={
        step > 1 && step < 4
          ? intl.formatMessage({ id: "label.button.back" })
          : null
      }
      onRequestSubmit={() => {
        if (step === 1 && file) setStep(2);
        else if (step === 2) handlePreview();
        else if (step === 3) handleImport();
        else handleClose();
      }}
      onSecondarySubmit={() => setStep(step - 1)}
      primaryButtonDisabled={
        (step === 1 && !file) ||
        (step === 2 && !requiredColumnsMapped) ||
        (step === 3 && previewErrors.length > 0) ||
        isPreviewLoading ||
        isImporting
      }
      size="lg"
    >
      <div className="manifest-import-modal">
        {step === 1 && (
          <div className="upload-step">
            <p className="step-description">
              <FormattedMessage
                id="notebook.immunology.manifest.step1"
                defaultMessage="Upload a CSV file with immunology sample reception metadata. Review the expected data points below before uploading."
              />
            </p>

            {/* Expected Data Points Section */}
            <Accordion className="expected-datapoints-accordion">
              <AccordionItem
                title={
                  <span className="accordion-title">
                    <Information size={16} />
                    <FormattedMessage
                      id="notebook.immunology.manifest.expectedColumns"
                      defaultMessage="Expected CSV Columns & Data Points"
                    />
                  </span>
                }
                open={!file}
              >
                <div className="datapoints-container">
                  {/* Required Fields */}
                  <div className="datapoints-section">
                    <h5 className="section-title required-title">
                      <FormattedMessage
                        id="notebook.immunology.manifest.requiredFields"
                        defaultMessage="Required Fields"
                      />
                      <Tag type="red" size="sm">
                        {EXPECTED_DATA_POINTS.required.length}
                      </Tag>
                    </h5>
                    <StructuredListWrapper isCondensed>
                      <StructuredListHead>
                        <StructuredListRow head>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.column"
                              defaultMessage="Column"
                            />
                          </StructuredListCell>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.description"
                              defaultMessage="Description"
                            />
                          </StructuredListCell>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.example"
                              defaultMessage="Example"
                            />
                          </StructuredListCell>
                        </StructuredListRow>
                      </StructuredListHead>
                      <StructuredListBody>
                        {EXPECTED_DATA_POINTS.required.map((field) => (
                          <StructuredListRow key={field.key}>
                            <StructuredListCell>
                              <strong>{field.label}</strong>
                              <br />
                              <code className="column-key">{field.key}</code>
                            </StructuredListCell>
                            <StructuredListCell>
                              {field.description}
                            </StructuredListCell>
                            <StructuredListCell>
                              <code>{field.example}</code>
                            </StructuredListCell>
                          </StructuredListRow>
                        ))}
                      </StructuredListBody>
                    </StructuredListWrapper>
                  </div>

                  {/* Sample Type Field (Validated) */}
                  <div className="datapoints-section">
                    <h5 className="section-title sampletype-title">
                      <FormattedMessage
                        id="notebook.immunology.manifest.sampleTypeField"
                        defaultMessage="Sample Type (Validated)"
                      />
                      <Tag type="purple" size="sm">
                        1
                      </Tag>
                    </h5>
                    <StructuredListWrapper isCondensed>
                      <StructuredListHead>
                        <StructuredListRow head>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.column"
                              defaultMessage="Column"
                            />
                          </StructuredListCell>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.description"
                              defaultMessage="Description"
                            />
                          </StructuredListCell>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="notebook.immunology.manifest.validValues"
                              defaultMessage="Valid Values"
                            />
                          </StructuredListCell>
                        </StructuredListRow>
                      </StructuredListHead>
                      <StructuredListBody>
                        <StructuredListRow>
                          <StructuredListCell>
                            <strong>
                              {EXPECTED_DATA_POINTS.sampleType.label}
                            </strong>
                            <br />
                            <code className="column-key">
                              {EXPECTED_DATA_POINTS.sampleType.key}
                            </code>
                          </StructuredListCell>
                          <StructuredListCell>
                            {EXPECTED_DATA_POINTS.sampleType.description}
                          </StructuredListCell>
                          <StructuredListCell>
                            <div className="valid-values-list">
                              {isSampleTypesLoading ? (
                                <Loading
                                  small
                                  withOverlay={false}
                                  description="Loading sample types..."
                                />
                              ) : validSampleTypes.length > 0 ? (
                                validSampleTypes.map((value, idx) => (
                                  <Tag key={idx} type="outline" size="sm">
                                    {value}
                                  </Tag>
                                ))
                              ) : (
                                <span className="no-sample-types">
                                  <FormattedMessage
                                    id="notebook.immunology.manifest.noSampleTypes"
                                    defaultMessage="No sample types configured. Contact administrator."
                                  />
                                </span>
                              )}
                            </div>
                          </StructuredListCell>
                        </StructuredListRow>
                      </StructuredListBody>
                    </StructuredListWrapper>
                  </div>

                  {/* Optional Fields */}
                  <div className="datapoints-section">
                    <h5 className="section-title optional-title">
                      <FormattedMessage
                        id="notebook.immunology.manifest.optionalFields"
                        defaultMessage="Optional Fields"
                      />
                      <Tag type="blue" size="sm">
                        {EXPECTED_DATA_POINTS.optional.length}
                      </Tag>
                    </h5>
                    <StructuredListWrapper isCondensed>
                      <StructuredListHead>
                        <StructuredListRow head>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.column"
                              defaultMessage="Column"
                            />
                          </StructuredListCell>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.description"
                              defaultMessage="Description"
                            />
                          </StructuredListCell>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.example"
                              defaultMessage="Example"
                            />
                          </StructuredListCell>
                        </StructuredListRow>
                      </StructuredListHead>
                      <StructuredListBody>
                        {EXPECTED_DATA_POINTS.optional.map((field) => (
                          <StructuredListRow key={field.key}>
                            <StructuredListCell>
                              <strong>{field.label}</strong>
                              <br />
                              <code className="column-key">{field.key}</code>
                            </StructuredListCell>
                            <StructuredListCell>
                              {field.description}
                            </StructuredListCell>
                            <StructuredListCell>
                              <code>{field.example}</code>
                            </StructuredListCell>
                          </StructuredListRow>
                        ))}
                      </StructuredListBody>
                    </StructuredListWrapper>
                  </div>

                  {/* Auto-Generated Fields */}
                  <div className="datapoints-section">
                    <h5 className="section-title auto-title">
                      <FormattedMessage
                        id="notebook.immunology.manifest.autoGeneratedFields"
                        defaultMessage="Auto-Generated Fields (Do not include in CSV)"
                      />
                      <Tag type="green" size="sm">
                        {EXPECTED_DATA_POINTS.autoGenerated.length}
                      </Tag>
                    </h5>
                    <StructuredListWrapper isCondensed>
                      <StructuredListHead>
                        <StructuredListRow head>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.field"
                              defaultMessage="Field"
                            />
                          </StructuredListCell>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.description"
                              defaultMessage="Description"
                            />
                          </StructuredListCell>
                        </StructuredListRow>
                      </StructuredListHead>
                      <StructuredListBody>
                        {EXPECTED_DATA_POINTS.autoGenerated.map((field) => (
                          <StructuredListRow key={field.key}>
                            <StructuredListCell>
                              <strong>{field.label}</strong>
                            </StructuredListCell>
                            <StructuredListCell>
                              {field.description}
                            </StructuredListCell>
                          </StructuredListRow>
                        ))}
                      </StructuredListBody>
                    </StructuredListWrapper>
                  </div>
                </div>
              </AccordionItem>
            </Accordion>

            {/* File Upload */}
            <div className="file-upload-section">
              {!file ? (
                <FileUploaderDropContainer
                  accept={[".csv"]}
                  labelText={intl.formatMessage({
                    id: "notebook.immunology.manifest.dropzone",
                    defaultMessage:
                      "Drag and drop a CSV file here or click to upload",
                  })}
                  onAddFiles={handleFileAdded}
                />
              ) : (
                <FileUploaderItem
                  name={file.name}
                  status="edit"
                  onDelete={handleRemoveFile}
                />
              )}
            </div>
            {fileError && (
              <InlineNotification
                kind="error"
                title={fileError}
                lowContrast
                hideCloseButton
              />
            )}
          </div>
        )}

        {step === 2 && (
          <div className="mapping-step">
            <p className="step-description">
              <FormattedMessage
                id="notebook.immunology.manifest.step2"
                defaultMessage="Map your CSV columns to the expected reception metadata fields. All required fields (marked with *) must be mapped."
              />
            </p>

            {/* Required Fields Section */}
            <div className="mapping-section">
              <h5 className="mapping-section-title">
                <FormattedMessage
                  id="notebook.immunology.manifest.requiredMappings"
                  defaultMessage="Required Fields"
                />
                <Tag type="red" size="sm">
                  6
                </Tag>
              </h5>
              <div className="mapping-grid">
                <div className="mapping-field required">
                  {mappingField(
                    "uniqueParentSampleIdColumn",
                    "notebook.immunology.manifest.column.uniqueParentSampleId",
                  )}
                  <span className="required-marker">*</span>
                </div>
                <div className="mapping-field required">
                  {mappingField(
                    "projectNameIdColumn",
                    "notebook.immunology.manifest.column.projectNameId",
                  )}
                  <span className="required-marker">*</span>
                </div>
                <div className="mapping-field required">
                  {mappingField(
                    "deliveryManifestReferenceColumn",
                    "notebook.immunology.manifest.column.deliveryManifestReference",
                  )}
                  <span className="required-marker">*</span>
                </div>
                <div className="mapping-field required">
                  {mappingField(
                    "collectionDateTimeColumn",
                    "notebook.immunology.manifest.column.collectionDateTime",
                  )}
                  <span className="required-marker">*</span>
                </div>
                <div className="mapping-field required">
                  {mappingField(
                    "receptionDateTimeColumn",
                    "notebook.immunology.manifest.column.receptionDateTime",
                  )}
                  <span className="required-marker">*</span>
                </div>
                <div className="mapping-field required">
                  {mappingField(
                    "sourceOriginColumn",
                    "notebook.immunology.manifest.column.sourceOrigin",
                  )}
                  <span className="required-marker">*</span>
                </div>
              </div>
            </div>

            {/* Sample Type Field Section (Validated) */}
            <div className="mapping-section">
              <h5 className="mapping-section-title">
                <FormattedMessage
                  id="notebook.immunology.manifest.sampleTypeMappings"
                  defaultMessage="Sample Type (Validated)"
                />
                <Tag type="purple" size="sm">
                  1
                </Tag>
              </h5>
              <p className="mapping-section-info">
                <FormattedMessage
                  id="notebook.immunology.manifest.sampleTypeInfo"
                  defaultMessage="Sample type must match one of the valid Immunology lab types. Invalid types will be rejected during validation."
                />
              </p>
              <div className="mapping-grid">
                {mappingField(
                  "sampleTypeColumn",
                  "notebook.immunology.manifest.column.sampleType",
                )}
              </div>
            </div>

            {/* Optional Fields Section */}
            <div className="mapping-section">
              <h5 className="mapping-section-title">
                <FormattedMessage
                  id="notebook.immunology.manifest.optionalMappings"
                  defaultMessage="Optional Fields"
                />
                <Tag type="blue" size="sm">
                  7
                </Tag>
              </h5>
              <div className="mapping-grid">
                {mappingField(
                  "sampleVolumeColumn",
                  "notebook.immunology.manifest.column.sampleVolume",
                )}
                {mappingField(
                  "storageConditionOnArrivalColumn",
                  "notebook.immunology.manifest.column.storageConditionOnArrival",
                )}
                {mappingField(
                  "transportTemperatureColumn",
                  "notebook.immunology.manifest.column.transportTemperature",
                )}
                {mappingField(
                  "receivingPersonnelNameColumn",
                  "notebook.immunology.manifest.column.receivingPersonnelName",
                )}
                {mappingField(
                  "manifestVerificationStatusColumn",
                  "notebook.immunology.manifest.column.manifestVerificationStatus",
                )}
                {mappingField(
                  "patientIdColumn",
                  "notebook.immunology.manifest.column.patientId",
                )}
                {mappingField(
                  "notesColumn",
                  "notebook.immunology.manifest.column.notes",
                )}
              </div>
            </div>

            {previewErrors.length > 0 && (
              <InlineNotification
                kind="error"
                title={intl.formatMessage({
                  id: "notebook.manifest.validationErrors",
                  defaultMessage: "Validation Errors",
                })}
                subtitle={
                  <ul className="error-list">
                    {previewErrors.map((error, idx) => (
                      <li key={idx}>
                        {error.rowNumber > 0 ? `Row ${error.rowNumber}: ` : ""}
                        {error.message}
                      </li>
                    ))}
                  </ul>
                }
                lowContrast
                hideCloseButton
              />
            )}
          </div>
        )}

        {step === 3 && (
          <div className="preview-step">
            {isPreviewLoading ? (
              <Loading withOverlay={false} description="Loading preview..." />
            ) : (
              <>
                {previewErrors.length > 0 && (
                  <InlineNotification
                    kind="error"
                    title={intl.formatMessage({
                      id: "notebook.manifest.validationErrors",
                      defaultMessage: "Validation Errors",
                    })}
                    subtitle={
                      <ul className="error-list">
                        {previewErrors.map((error, idx) => (
                          <li key={idx}>
                            {error.rowNumber > 0
                              ? `Row ${error.rowNumber}: `
                              : ""}
                            {error.message}
                          </li>
                        ))}
                      </ul>
                    }
                    lowContrast
                    hideCloseButton
                  />
                )}

                {previewData && previewErrors.length === 0 && (
                  <div className="preview-summary">
                    <Tag type="blue">
                      <FormattedMessage
                        id="notebook.manifest.preview.rows"
                        defaultMessage="{count} rows"
                        values={{ count: previewData.totalRows }}
                      />
                    </Tag>
                    <Tag type="green">
                      <FormattedMessage
                        id="notebook.manifest.preview.samples"
                        defaultMessage="{count} samples to create"
                        values={{ count: previewData.totalSamplesToCreate }}
                      />
                    </Tag>
                  </div>
                )}
              </>
            )}
          </div>
        )}

        {step === 4 && (
          <div className="success-step">
            <Checkmark size={48} className="success-icon" />
            <h3>
              <FormattedMessage
                id="notebook.manifest.success.title"
                defaultMessage="Import Successful"
              />
            </h3>
            <p>
              <FormattedMessage
                id="notebook.immunology.manifest.success.message"
                defaultMessage="Immunology samples have been created and linked to the notebook entry with reception metadata."
              />
            </p>
          </div>
        )}
      </div>
    </Modal>
  );
}

export default ImmunologyManifestImportModal;
